version: "3.8"
services:
  backend:
    build: ./backend
    container_name: ecommerce-backend
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build: ./frontend
    container_name: ecommerce-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
