apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: ecommerce

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend
        image: sapna201/pro-backend:v1
        imagePullPolicy: Always

        ports:
        - containerPort: 5000
